version: '3.9'

services:
  distributedcache:
    image: redis:latest

  productdb:
    image: postgres

  categorydb:
    image: postgres

  branddb:
    image: postgres

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/Product/Product.API/Dockerfile

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  inventory.api:
    image: ${DOCKER_REGISTRY-}inventoryapi
    build:
      context: .
      dockerfile: Services/Inventory/Inventory.API/Dockerfile

  category.api:
    image: ${DOCKER_REGISTRY-}categoryapi
    build:
      context: .
      dockerfile: Services/Category/Category.API/Dockerfile

  brand.api:
    image: ${DOCKER_REGISTRY-}brandapi
    build:
      context: .
      dockerfile: Services/Brand/Brand.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_product:
  postgres_category:
  postgres_brand:
